package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();
    private Random rand = new Random();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    private User randomUserSelection() {
        List<User> randomUsers = new ArrayList<>(Arrays.asList());
        for (User user : FAKE_USERS_RANDOM) {
            if (!users.contains(user)) { randomUsers.add(user); }
        }
        if (randomUsers.isEmpty()) return null;
        int int_random = rand.nextInt(randomUsers.size());
        return randomUsers.get(int_random);
    }
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        User user = randomUserSelection();
        if (user != null) {
            users.add(user);
        }
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        users.remove(user);
    }
}
